name: URL scan

on:
  push:
    branches:
      - main
      - travail

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger analyze workflow
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               https://api.github.com/repos/LUniversiteNumerique/url-analyzer/dispatches \
               -d '{"event_type": "trigger_workflow"}'
